### ISSUE TITLE
dGPU re-enables itself sometimes after sleep

### ISSUE THREAD

**Issue by koluris** [dkoluris/ZEPHYRUS-M15-GU502-OpenCore#1]
While the laptop is able to maintain a 35C temperature with dGPU disabled by using the patched SSDT, it seems that sometimes the dGPU gets re-enabled after wake from sleep and system temperature rises to 50C on idle, which is really bad. Need to investigate possible solutions for this.

**Comment by Alex-V2000** [comment]
Man, I managed to solve this problem, which was already annoying!

**Comment by Alex-V2000** [comment]
I have a laptop with a very similar hardware also ROG and it looks identical to yours but very small differences!

**Comment by Alex-V2000** [comment]
So this solution is possible to work for you without any problem!

**Comment by Alex-V2000** [comment]
I will attach here later the two SSDTs you need!

**Comment by koluris** [comment]
Great stuff Alex! Looking forward to it!

**Comment by Alex-V2000** [comment]
[SSDTs.zip](https://github.com/dkoluris/ZEPHYRUS-M15-GU502-OpenCore/files/5879931/SSDTs.zip)
First remove SSDT-DGPUOFF.aml

**Comment by koluris** [comment]
That was pretty good, it works! I was able to include only the necessary to it (latest commit). Much appreciated, I will add you to the credits on the Readme for the awesome contribution :)

**Comment by Alex-V2000** [comment]
With great pleasure, man!

**Comment by koluris** [comment]
Alex-V2000 provided the solution to this problem.
