### ISSUE TITLE
[question] color profile

### ISSUE THREAD

**Issue by dnmTX** [dkoluris/ZEPHYRUS-M15-GU502-OpenCore#10]
@dkoluris i'm off topic here(sorry about that) but i was wondering about the color profile provided here,which is philips one.
I have the same laptop(the 4K version with RTX 2060) but on Windows. Could this color profile get me better colors or it's just specific for MacOS. Thanks 👍

**Comment by koluris** [comment]
Yes, this profile works like magic for me. I am using it on a MacBook Pro as well as the Asus laptop, and it makes colors pop just right on screen. Look up the procedure to select the color profile online in Windows, it's a little bit more complicated compared to the Mac.

**Comment by dnmTX** [comment]
Dennis @dkoluris thanks for this. I'll  definitely give it a try as i already figured how to change color profiles.
Take care 👍  Closing....

**Comment by dnmTX** [comment]
Dennis @dkoluris let me return the favor,as it looks like when searching the web for `.icc` profiles in general,it's all looks like some **hush hush** situation.No one offering,advising,nothing. Your repo here is one of three places that i found something usefull so...uploading here my original color profile. Again,same laptop as yours,just mine came with the 4K 60Hz screen( it's Pantone Validated,100% RGB bla bla and bla. All that marketing bull 😉 ) Test it,see if it's worth something,if it does,you can offer it here as one more additional choice for everyone 👍 👍 👍 

P.S. Had to add `.txt` extension at the end to let me upload it. Remove it and it's all good.
[GU502LV_8086_AF0631EB_CMDEF.icm.txt](https://github.com/dkoluris/ZEPHYRUS-M15-GU502-OpenCore/files/7731845/GU502LV_8086_AF0631EB_CMDEF.icm.txt)
