### ISSUE TITLE
Apple Watch

### ISSUE THREAD

**Issue by dxh000130** [dkoluris/ZEPHYRUS-M15-GU502-OpenCore#5]
Hey, did you try Apple Watch Unlock?

**Comment by blackbrut1** [comment]
> Hey, did you try Apple Watch Unlock?

**Comment by dxh000130** [comment]
> > Hey, did you try Apple Watch Unlock?

?

**Comment by koluris** [comment]
Don't have a watch to test :|

**Comment by Alex-V2000** [comment]
Not working apple watch unlock, because intel card kext not accept that !

**Comment by dxh000130** [comment]
> Not working apple watch unlock, because intel card kext not accept that !
I installed a bcm94360 in m2. Apple watch is available but not respond.
